### ISSUE TITLE
Bug: Submitting new job cannot succeed

### ISSUE THREAD

**Issue by strixaluco** [frappe/community_erpnext_com#11]
I'm having one more issue with community.erpnext.com/jobs — whenever I press "Submit" button in a "Post job" form, I have the next message:

> Message
> Cannot send this email. You have crossed the sending limit of 5000 emails for this month.

Tested on Firefox 38.7.1 ESR and Chromium 49.0.2623.108

**Comment by rmehta** [comment]
Fixed. Thanks for reporting!

**Comment by strixaluco** [comment]
Thank you for fix, @rmehta, it really worked and the job got posted! The only issue is that I received another message:

> Message
> info@ergonomicscitc=.com is not a valid email id

**Comment by strixaluco** [comment]
The following bug has been fixed by support team and now the process is passing fine, so I can close the issue.
