### ISSUE TITLE
Bug: Attempting to edit account profile at Jobs section cannot succeed

### ISSUE THREAD

**Issue by strixaluco** [frappe/community_erpnext_com#12]
It's me again having a problem at [community.erpnext.com/jobs](https://community.erpnext.com/jobs) section, following next steps:

Gravatar icon at top right → My account → Edit profile

Leads to the message like this:
> Page missing or moved
> 
> We are very sorry for this, but the page you are looking for is missing (this could be because of a typo in the address) or moved.

URL in the browser shows "https://community.erpnext.com/edit-profile"
Tested on Firefox 38.7.1 ESR and Chromium 49.0.2623.108

**Comment by rmehta** [comment]
Also fixed

**Comment by strixaluco** [comment]
Thanks.
