### ISSUE TITLE
Testimonials Section for Service Provider

### ISSUE THREAD

**Issue by syedqadeer** [frappe/community_erpnext_com#13]
Hello All,

The service provider profile section is missing the testimonial section.

Any client can goto a service provider profile and write a testimonial for him.

**Comment by rmehta** [comment]
Why don't you add it!

**Comment by syedqadeer** [comment]
you mean whenever a customer write a testimonial for me , i will add it manually into the description of my service provider profile ??

**Comment by rmehta** [comment]
or make the feature and send a pull-request.

**Comment by saurabh6790** [comment]
Update testimonials via service partner form in markdown or textual form

<img width="542" alt="screen shot 2016-09-14 at 4 50 57 pm" src="https://cloud.githubusercontent.com/assets/3784093/18510432/a33d9b44-7a9b-11e6-874e-b1bcd490332b.png">

View

<img width="646" alt="screen shot 2016-09-14 at 4 49 38 pm" src="https://cloud.githubusercontent.com/assets/3784093/18510448/babc4928-7a9b-11e6-9ddc-11618054a4c8.png">
