### ISSUE TITLE
is html allows in Introduction [service providers page]? 

### ISSUE THREAD

**Issue by sbkolate** [frappe/community_erpnext_com#3]
It good feature to allow html code in **Description**  (Service provider can design their page)

But if you are allowing html code in Introduction and may user write wrong code like unclosed html tag,
then it will break others listing

Please let me know, you are allowing or not to design Introduction.

**Comment by rmehta** [comment]
@sbkolate  please don't add html in your introduction. Can you remove your current HTML? Thanks.

**Comment by sbkolate** [comment]
Thanks, just removed html from description 
https://community.erpnext.com/service-providers?country=India
